### PR TITLE
add PNG version of logo with a transparent background

### PR DESCRIPTION
**Pull request by grlee77**
I added a version of the existing PNG logo where the background outside of the central circle is set to transparent (but the central "S" is still in white).

I think if we use this version for the organization profile picture on GitHub, it will look better with the dark theme while still appearing the same as the current one with the light theme. What do you think?

### CODE REVIEW

**Comment by grlee77** [comment]
This is how the current logo without the transparent background looks now. The white square around the circular region would not be shown with the version proposed here.


_skimage_current

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
I'm into it. We still need that new logo :joy: but this will improve things in the meantime. I'll let this sit for 24h in case @stefanv or other team members have comments, otherwise I'll merge tomorrow.

**Comment by stefanv** [comment]
Go for it! Did you re-render this with transparent background using the logo script, or did you edit the existing png in skimage or gimp? The prior approach should give better results.

**Comment by grlee77** [comment]
> Go for it! Did you re-render this with transparent background using the logo script, or did you edit the existing png in skimage or gimp?

I just edited the existing PNG. I had opened an SVG file in that folder first, but it just had a copy of the PNG embedded. I had not looked at the Python script, though

**Comment by grlee77** [comment]
Okay, I have now regenerated it using the script. Thanks for pointing that out @stefanv!

**Comment by grlee77** [comment]
I think one of you would have to update the logo in the organization settings, I do not seem to have permissions for that.

**Comment by stefanv** [comment]
You should be able to now.

**Comment by stefanv** [comment]
Thanks for the new logo!

**Comment by grlee77** [comment]
I changed it on the organization and it looks like this in Dark mode (apparently GitHub inserts its own dark-gray background):
_dark

Before uploading the icon, I did manually trim the white S by a few pixels on each end because it was sticking out very slightly past the circle extent. Let me know if you prefer I commit that trimmed version here instead of the one generated directly by the script.

**Comment by stefanv** [comment]
Looks good; thanks, Greg!  Weird that GitHub would mismatch their own background color :man_shrugging:

**Comment by stefanv** [comment]
Another option would be to take the white out completely, and to have that be the background color too.

**Pull request merged**
