### PR TITLE
Add sticker design

### PR DESCRIPTION
**Pull request by stefanv**
Note that the sticker will not include the gray part--this is included to illustrate how it would look on, e.g., a laptop.

The exact size still has to be determined.

sticker_00

### CODE REVIEW

**Comment by blink1073** [comment]
Looks good!

**Comment by almarklein** [comment]
Is someone going to bring these to Euroscipy this year? I'd love one :)

**Comment by glyg** [comment]
@almarklein +1 !

**Comment by stefanv** [comment]
@almarklein We can have some printed, no problem.  Please follow up with me mid-July.

**Pull request merged**
